<a href="https://colab.research.google.com/github/marcospnur/Codigos/blob/main/Libro_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  5- Tratamiento de datos con Python

## 5.3 Numpy

In [ ]:
import numpy as np

#creando variable
v1= np.array([1,2,3,4,5,6,7,8,9,0])
v1

#varificando el tipo de dato
v1.dtype

#definiendo la dimension del dato
v1.ndim

#dimensión de matriz
v2= np.array([[1,2,3],[4,5,6],[7,8,9]])
v2.shape

#creando matriz de 1
v3= np.ones((3,3))
v3

#creando matriz de 0
v4= np.zeros((3,3))
v4

#creando matriz diagonal
v5= np.eye(4,4)
v5

#creando secuencia
v6= np.arange(10)
v6

#seleccionando elementos
v6[3]
v2[1,2]
v2[:,1]
v2[0:2,1]

#Números aleatorios
v7= np.random.rand(5,5)
v7.round(2)

#algebra arrays
array1=np.arange(5)
array2=np.random.rand(5)
array1+array2

#operaciones numericas
np.sqrt(4)
np.exp(2)
np.log(np.exp(1))
np.log10(np.exp(1))

np.max(v6)
np.min(v6)
np.argmax(v6)
np.argmin(v6)

np.sum(v6)
np.mean(v6)
np.std(v6)
np.var(v6)

#concatenar
np.vstack((v6,v1))
np.hstack((v6,v1))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

## 5.4 SCIPY

In [ ]:
import scipy as sp
# proporciona rutinas numericas como
# Integracion
# Optimización
# Operaciones estadísticas
# Clusters
# Procesado de imagenes y señales.

## 5.5 Pandas

In [ ]:
import pandas as pd
# permite el manejo de estructuras de datos y herramientas de analisis.
# los diferentes datos pueden ser
# tabulados
# series
# data frames
# panel, panel 4d y panelND

### 5.5.1 Estructura de datos en pandas

In [ ]:
pd.Series([1,3,5,np.nan, 6 , 8])

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
dates=pd.date_range("20210101", periods=6)
pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))

                   A         B         C         D
2021-01-01  0.633885  1.132057  1.230511 -0.910809
2021-01-02 -1.327674  1.242217 -0.440568  1.427777
2021-01-03 -1.787064  0.117465  0.518004 -2.460016
2021-01-04  0.268217  0.755781 -1.508980 -0.117082
2021-01-05 -0.974181 -0.255391 -0.762596  1.049479
2021-01-06 -1.809273 -1.097698 -1.032505  0.278831

In [ ]:
key=["Key1", "key2"]
left=pd.DataFrame({"key":key, "lval":[1,2]})
rigth=pd.DataFrame({"key":key, "rval":[5,6]})

concat= pd.concat([left,rigth])

merge=pd.merge(left,rigth, on="key")

print(left)
print("-"*15)
print(rigth)
print("-"*15)
print(concat)
print("-"*15)
print(merge)

    key  lval
0  Key1     1
1  key2     2
---------------
    key  rval
0  Key1     5
1  key2     6
---------------
    key  lval  rval
0  Key1   1.0   NaN
1  key2   2.0   NaN
0  Key1   NaN   5.0
1  key2   NaN   6.0
---------------
    key  lval  rval
0  Key1     1     5
1  key2     2     6

### 5.5.2 Series

In [ ]:
data1=[1,2,3,4,5]
serie1 = pd.Series(data1)

serie1.index

serie1.index=["Index 0", "Index 1","Index 2","Index 3","Index 4"]

serie1=pd.Series(data1, index=["Index 0", "Index 1","Index 2","Index 3","Index 4"])

serie2=pd.Series(["Primera posicion","Segunda posicion","Tercera posicion","Cuarta posicion","Quinta posicion"], index=["Index 0", "Index 1","Index 2","Index 3","Index 4"])
serie2.name="Serie de datos"
#

print(serie1)
print("-"*15)
print(serie1[1])
print("-"*15)
print(serie1[:4])
print("-"*15)
print(serie1["Index 1": "Index 3"])
print("-"*15)
print(serie1>3)
print("-"*15)
print(serie2)

Index 0    1
Index 1    2
Index 2    3
Index 3    4
Index 4    5
dtype: int64
---------------
2
---------------
Index 0    1
Index 1    2
Index 2    3
Index 3    4
dtype: int64
---------------
Index 1    2
Index 2    3
Index 3    4
dtype: int64
---------------
Index 0    False
Index 1    False
Index 2    False
Index 3     True
Index 4     True
dtype: bool
---------------
Index 0    Primera posicion
Index 1    Segunda posicion
Index 2    Tercera posicion
Index 3     Cuarta posicion
Index 4     Quinta posicion
Name: Serie de datos, dtype: object

/tmp/ipykernel_18518/2352154200.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(serie1[1])

### 5.5.3 DataFrame

In [ ]:
data=[1,2,3,4,5]
df=pd.DataFrame(data, index=["index 0","index 1","index 2","index 3","index 4"])
df

         0
index 0  1
index 1  2
index 2  3
index 3  4
index 4  5

In [ ]:
df2=pd.DataFrame({"datos1":[1,2,3,4,5], "datos2":["a","b","c","d","e"]}, index=["index 1","index 2", "index 3", "index 4", "index 5"])
df2

         datos1 datos2
index 1       1      a
index 2       2      b
index 3       3      c
index 4       4      d
index 5       5      e

In [ ]:
print(type(df2["datos1"]))
print(type(df2["datos2"]))
print(df2["datos1"])
print(df2["datos2"])

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
index 1    1
index 2    2
index 3    3
index 4    4
index 5    5
Name: datos1, dtype: int64
index 1    a
index 2    b
index 3    c
index 4    d
index 5    e
Name: datos2, dtype: object

In [ ]:
print(df2.loc["index 4"])
print(df2.loc["index 4", "datos1"])
print(df2.loc["index 2", "datos2"])

datos1    4
datos2    d
Name: index 4, dtype: object
4
b

In [ ]:
df2.reindex(["index 5", "index 4", "index 3", "index 2", "index 1"])

         datos1 datos2
index 5       5      e
index 4       4      d
index 3       3      c
index 2       2      b
index 1       1      a

In [ ]:
df2.apply(lambda x: [max(x), min(x)])#, index=["max", "min"])

   datos1 datos2
0       5      e
1       1      a

In [ ]:
df2['datos1'].apply(lambda x: x*x)

index 1     1
index 2     4
index 3     9
index 4    16
index 5    25
Name: datos1, dtype: int64

In [ ]:
df2['datos1'].mean()

np.float64(3.0)

In [ ]:
df2['datos1'].sum()

np.int64(15)

In [ ]:
df2["datos1"].tolist()

[1, 2, 3, 4, 5]

In [ ]:
df2[df2["datos1"]>2]

         datos1 datos2
index 3       3      c
index 4       4      d
index 5       5      e

# 6 - Scikit-learn como libreria de machine learning